import Navbar from "../components/navbar/Navbar";
// import Footer from "../components/footer/Footer";
import "./global.css";

export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar></Navbar> */}
        {children}
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
